name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^0.39.5
  build: ^1.3.0
  code_builder: ^3.4.1
  collection: ^1.14.13
  dart_style: ^1.3.6
  logging: 1.0.1
  meta: ^1.1.8
  path: ^1.7.0
  quiver: ^2.1.3
  stack_trace: ^1.9.5

dev_dependencies:
  build_runner: ^1.10.1
  build_test: ^1.2.1
  inject:
    path: ../inject
  test: ^1.15.3
